export const METHODS = {
  gdi: {
    label: "Genetic Diversity Index (GDI)",
    plain:
      "A single composite 0–100 headline for the genetic health of the scope.",
    formula:
      "Normalised equal blend of mean He, rarefied allelic richness, and (1 − mean kinship), scaled 0–100.",
    estimator: "Composite (configurable weights; default equal thirds).",
    assumption:
      "Weights are transparent and adjustable; not a published index.",
    citation: "AiQL composite (this build).",
  },
  he: {
    label: "Expected heterozygosity (He)",
    plain: "Gene diversity — the chance two random alleles at a locus differ.",
    formula: "He = 1 − Σpᵢ²",
    estimator: "Nei (1973), unbiased over loci.",
    assumption: "Random-mating reference.",
    citation: "Nei 1973.",
  },
  ho: {
    label: "Observed heterozygosity (Ho)",
    plain: "Proportion of individuals heterozygous at a locus.",
    formula: "Ho = heterozygotes / typed individuals",
    estimator: "Direct count.",
    assumption: "—",
    citation: "—",
  },
  na: {
    label: "Number of alleles (Na)",
    plain: "Distinct alleles observed at a locus.",
    formula: "count of distinct alleles",
    estimator: "Direct count (sample-size sensitive).",
    assumption: "Larger samples find more alleles.",
    citation: "—",
  },
  ar: {
    label: "Allelic richness (Ar)",
    plain:
      "Allele count standardised for sample size so cohorts compare fairly.",
    formula: "rarefaction to a common sample size g",
    estimator: "El Mousadik & Petit (1996).",
    assumption: "Enables fair cross-cohort comparison.",
    citation: "El Mousadik & Petit 1996.",
  },
  ne_alleles: {
    label: "Effective number of alleles (Ne)",
    plain: "Alleles weighted by frequency — evenness of the allele spectrum.",
    formula: "Ne = 1 / Σpᵢ² = 1 / (1 − He)",
    estimator: "From allele frequencies.",
    assumption: "—",
    citation: "—",
  },
  pic: {
    label: "Polymorphic Information Content (PIC)",
    plain: "How informative a marker is for distinguishing individuals.",
    formula: "PIC = 1 − Σpᵢ² − Σ Σ 2pᵢ²pⱼ²",
    estimator: "Botstein et al. (1980).",
    assumption: "Per-locus.",
    citation: "Botstein 1980.",
  },
  f: {
    label: "Individual inbreeding (F)",
    plain: "Excess homozygosity in an individual relative to expectation.",
    formula: "HL / IR / molecular-F vs HWE expectation",
    estimator: "Homozygosity by Loci (Aparicio 2006); ≥2 estimators offered.",
    assumption: "Population allele frequencies required.",
    citation: "Aparicio 2006; Amos 2001.",
  },
  kinship: {
    label: "Kinship θ",
    plain: "Probability two alleles (one per animal) are identical by descent.",
    formula: "moment estimator from allele sharing, frequency-weighted",
    estimator: "Moment estimator.",
    assumption: "Population allele frequencies required.",
    citation: "—",
  },
  relatedness: {
    label: "Relatedness r",
    plain: "Proportion of alleles shared identical-by-descent (≈ 2θ).",
    formula: "frequency-aware pairwise estimator",
    estimator: "Queller & Goodnight (1989) — default; Lynch & Ritland; Wang.",
    assumption: "Population allele frequencies required.",
    citation: "Queller & Goodnight 1989.",
  },
  ne: {
    label: "Effective population size (Ne)",
    plain:
      "The size of an idealised population losing diversity at the same rate.",
    formula: "Ne ≈ 1 / (2 · mean kinship) — coancestry method",
    estimator: "Coancestry (headline); LD method (Waples) secondary.",
    assumption: "Report method + CI.",
    citation: "Waples 2006.",
  },
  fst: {
    label: "F_ST (differentiation)",
    plain: "How genetically distinct two subpopulations are.",
    formula: "θ (Weir & Cockerham); Nei's Gst variant",
    estimator: "Weir & Cockerham (1984).",
    assumption: "≥2 cohorts.",
    citation: "Weir & Cockerham 1984.",
  },
  hwe: {
    label: "Hardy–Weinberg equilibrium (HWE)",
    plain: "Whether genotype proportions match random-mating expectation.",
    formula: "exact test; flags null alleles / structure",
    estimator: "Guo & Thompson (1992) exact test.",
    assumption: "Deviation can indicate null alleles or substructure.",
    citation: "Guo & Thompson 1992.",
  },
  cpe: {
    label: "Combined exclusion power (CPE)",
    plain: "Probability the panel excludes a wrongly-declared parent.",
    formula: "CPE = 1 − Π(1 − PEₗ) over loci",
    estimator: "Combined over loci (Master §6.2).",
    assumption: "Panel-level.",
    citation: "Jamieson & Taylor 1997.",
  },
  pi: {
    label: "Probability of identity (PI / PI-sibs)",
    plain: "Chance two animals share a genotype by chance (individualisation).",
    formula: "product over loci of per-locus match probability",
    estimator: "Standard PI and PI-sibs.",
    assumption: "PI-sibs is the conservative bound.",
    citation: "Waits et al. 2001.",
  },
};
